spring:
  application:
    name: EUREKA-HA
eureka:
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 5000
---
server:
  port: 8761
spring:
  profiles: eureka1
eureka:
  instance:
    hostname: eureka1
    instance-id: eureka1--8761
  client:
    serviceUrl:
      defaultZone: http://eureka2:8762/eureka/,http://eureka3:8763/eureka/
---
server:
  port: 8762
spring:
  profiles: eureka2
eureka:
  instance:
    hostname: eureka2
    instance-id: eureka2--8762
  client:
    serviceUrl:
      defaultZone: http://eureka1:8761/eureka/,http://eureka3:8763/eureka/
---
server:
  port: 8763
spring:
  profiles: eureka3
eureka:
  instance:
    hostname: eureka3
    instance-id: eureka3--8763
  client:
    serviceUrl:
      defaultZone: http://eureka2:8762/eureka/,http://eureka1:8761/eureka/