spring:
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
  datasource:
    url: jdbc:mysql://10.255.33.109:3306/uc_push?characterEncoding=utf8&useSSL=true&autoReconnect=true&allowMultiQueries=true
    username: infra
    password: pwd_infra
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 0
      max-active: 100
      min-idle: 20
      max-wait: 60000
      validation-query: SELECT 1
      validation-query-timeout: 3000
      test-on-borrow: true
      test-on-return: true
      test-while-idle: true
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 25200000
      remove-abandoned: true
      log-abandoned: true
mybatis:
  configuration:
    map-underscore-to-camel-case: true
######rabbit my#################
rabbitmq:
  host: 10.255.33.108:5674
  username: admin
  password: admin
  springCloudBus: /
  virtualHostCommon: vhost.common60
  virtualHostInfra: vhost.infra