spring:
  application:
    name: jw-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/jiaweisoft/jw-config-github.git  #{application}
          username: jiaweisoft@163.com
          password: 2010080189you
          search-paths: '{application}'
    bus:
      enabled: true
  security:
    user:
      name: jiawei
      password: jiawei
eureka:
  instance:
    hostname: ${spring.cloud.client.ip-address}
    instance-id: ${eureka.instance.hostname}:----:${server.port}
    lease-renewal-interval-in-seconds: 3 #每30秒一次renewal
    lease-expiration-duration-in-seconds: 9 #90秒没有rennewal剔除
  client:
    service-url:
      default-zone: http://eureka1:8761/eureka/,http://eureka2:8762/eureka/
######rabbit my#################
rabbitmq:
  host: ${rabbitmq.addresses}
  username: ${rabbitmq.username}
  password: ${rabbitmq.password}
  springCloudBus: ${rabbitmq.spring.cloud.bus}